# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Powell Quiring
tagline:          'Getting it done'
description:      'Software development by <a href="https://twitter.com/powellquiring" target="_blank">@powellquiring</a>.'
url:              http://powellquiring.github.io
baseurl:          /

author:
  name:           'Powell Quiring'
  url:            https://twitter.com/powellquiring

paginate:         1

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/powellquiring/powellquiring.github.io
